// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.6.1
// source: protos/cronjob_controller.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlCronjobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartCronjob bool `protobuf:"varint,1,opt,name=startCronjob,proto3" json:"startCronjob,omitempty"` // true to start, false to stop
}

func (x *ControlCronjobRequest) Reset() {
	*x = ControlCronjobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cronjob_controller_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlCronjobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlCronjobRequest) ProtoMessage() {}

func (x *ControlCronjobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cronjob_controller_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlCronjobRequest.ProtoReflect.Descriptor instead.
func (*ControlCronjobRequest) Descriptor() ([]byte, []int) {
	return file_protos_cronjob_controller_proto_rawDescGZIP(), []int{0}
}

func (x *ControlCronjobRequest) GetStartCronjob() bool {
	if x != nil {
		return x.StartCronjob
	}
	return false
}

type ControlCronjobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ControlCronjobResponse) Reset() {
	*x = ControlCronjobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cronjob_controller_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlCronjobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlCronjobResponse) ProtoMessage() {}

func (x *ControlCronjobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cronjob_controller_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlCronjobResponse.ProtoReflect.Descriptor instead.
func (*ControlCronjobResponse) Descriptor() ([]byte, []int) {
	return file_protos_cronjob_controller_proto_rawDescGZIP(), []int{1}
}

func (x *ControlCronjobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ControlCronjobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CronjobStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Running bool `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
}

func (x *CronjobStatus) Reset() {
	*x = CronjobStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cronjob_controller_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CronjobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronjobStatus) ProtoMessage() {}

func (x *CronjobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cronjob_controller_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronjobStatus.ProtoReflect.Descriptor instead.
func (*CronjobStatus) Descriptor() ([]byte, []int) {
	return file_protos_cronjob_controller_proto_rawDescGZIP(), []int{2}
}

func (x *CronjobStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

type CronjobStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Running bool `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
}

func (x *CronjobStatusResponse) Reset() {
	*x = CronjobStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cronjob_controller_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CronjobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronjobStatusResponse) ProtoMessage() {}

func (x *CronjobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cronjob_controller_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronjobStatusResponse.ProtoReflect.Descriptor instead.
func (*CronjobStatusResponse) Descriptor() ([]byte, []int) {
	return file_protos_cronjob_controller_proto_rawDescGZIP(), []int{3}
}

func (x *CronjobStatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

var File_protos_cronjob_controller_proto protoreflect.FileDescriptor

var file_protos_cronjob_controller_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x72, 0x6f, 0x6e, 0x6a, 0x6f, 0x62,
	0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x3b,
	0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x43, 0x72, 0x6f, 0x6e, 0x6a, 0x6f, 0x62,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x43, 0x72, 0x6f, 0x6e, 0x6a, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x43, 0x72, 0x6f, 0x6e, 0x6a, 0x6f, 0x62, 0x22, 0x4c, 0x0a, 0x16, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x43, 0x72, 0x6f, 0x6e, 0x6a, 0x6f, 0x62, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x29, 0x0a, 0x0d, 0x43, 0x72, 0x6f,
	0x6e, 0x6a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x75, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x22, 0x31, 0x0a, 0x15, 0x43, 0x72, 0x6f, 0x6e, 0x6a, 0x6f, 0x62, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x32, 0xc2, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x6f, 0x6e,
	0x6a, 0x6f, 0x62, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x59, 0x0a,
	0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x43, 0x72, 0x6f, 0x6e, 0x6a, 0x6f, 0x62, 0x12,
	0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x43, 0x72, 0x6f, 0x6e, 0x6a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x43, 0x72, 0x6f, 0x6e, 0x6a, 0x6f, 0x62,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x43,
	0x72, 0x6f, 0x6e, 0x6a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x6f, 0x6e, 0x6a,
	0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x6f, 0x6e, 0x6a, 0x6f, 0x62, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_cronjob_controller_proto_rawDescOnce sync.Once
	file_protos_cronjob_controller_proto_rawDescData = file_protos_cronjob_controller_proto_rawDesc
)

func file_protos_cronjob_controller_proto_rawDescGZIP() []byte {
	file_protos_cronjob_controller_proto_rawDescOnce.Do(func() {
		file_protos_cronjob_controller_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_cronjob_controller_proto_rawDescData)
	})
	return file_protos_cronjob_controller_proto_rawDescData
}

var file_protos_cronjob_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_cronjob_controller_proto_goTypes = []interface{}{
	(*ControlCronjobRequest)(nil),  // 0: grpc_server.ControlCronjobRequest
	(*ControlCronjobResponse)(nil), // 1: grpc_server.ControlCronjobResponse
	(*CronjobStatus)(nil),          // 2: grpc_server.CronjobStatus
	(*CronjobStatusResponse)(nil),  // 3: grpc_server.CronjobStatusResponse
}
var file_protos_cronjob_controller_proto_depIdxs = []int32{
	0, // 0: grpc_server.CronjobController.controlCronjob:input_type -> grpc_server.ControlCronjobRequest
	2, // 1: grpc_server.CronjobController.getCronjobStatus:input_type -> grpc_server.CronjobStatus
	1, // 2: grpc_server.CronjobController.controlCronjob:output_type -> grpc_server.ControlCronjobResponse
	3, // 3: grpc_server.CronjobController.getCronjobStatus:output_type -> grpc_server.CronjobStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_cronjob_controller_proto_init() }
func file_protos_cronjob_controller_proto_init() {
	if File_protos_cronjob_controller_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_cronjob_controller_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlCronjobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_cronjob_controller_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlCronjobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_cronjob_controller_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CronjobStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_cronjob_controller_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CronjobStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_cronjob_controller_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_cronjob_controller_proto_goTypes,
		DependencyIndexes: file_protos_cronjob_controller_proto_depIdxs,
		MessageInfos:      file_protos_cronjob_controller_proto_msgTypes,
	}.Build()
	File_protos_cronjob_controller_proto = out.File
	file_protos_cronjob_controller_proto_rawDesc = nil
	file_protos_cronjob_controller_proto_goTypes = nil
	file_protos_cronjob_controller_proto_depIdxs = nil
}
