// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: protos/slack.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SlackServiceClient is the client API for SlackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SlackServiceClient interface {
	SendMessage(ctx context.Context, in *SlackMessageRequest, opts ...grpc.CallOption) (*SlackMessageResponse, error)
}

type slackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSlackServiceClient(cc grpc.ClientConnInterface) SlackServiceClient {
	return &slackServiceClient{cc}
}

func (c *slackServiceClient) SendMessage(ctx context.Context, in *SlackMessageRequest, opts ...grpc.CallOption) (*SlackMessageResponse, error) {
	out := new(SlackMessageResponse)
	err := c.cc.Invoke(ctx, "/slack.SlackService/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SlackServiceServer is the server API for SlackService service.
// All implementations must embed UnimplementedSlackServiceServer
// for forward compatibility
type SlackServiceServer interface {
	SendMessage(context.Context, *SlackMessageRequest) (*SlackMessageResponse, error)
	mustEmbedUnimplementedSlackServiceServer()
}

// UnimplementedSlackServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSlackServiceServer struct {
}

func (UnimplementedSlackServiceServer) SendMessage(context.Context, *SlackMessageRequest) (*SlackMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedSlackServiceServer) mustEmbedUnimplementedSlackServiceServer() {}

// UnsafeSlackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SlackServiceServer will
// result in compilation errors.
type UnsafeSlackServiceServer interface {
	mustEmbedUnimplementedSlackServiceServer()
}

func RegisterSlackServiceServer(s grpc.ServiceRegistrar, srv SlackServiceServer) {
	s.RegisterService(&SlackService_ServiceDesc, srv)
}

func _SlackService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlackMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlackServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slack.SlackService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlackServiceServer).SendMessage(ctx, req.(*SlackMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SlackService_ServiceDesc is the grpc.ServiceDesc for SlackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SlackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "slack.SlackService",
	HandlerType: (*SlackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _SlackService_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/slack.proto",
}
