name: CI - Notifications

on:
  push:
    branches:
      - main
    paths:
      - 'app/server/ArgoCD/Notifications/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/server/ArgoCD/Notifications/**'
      
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build Packages
        working-directory: ./app/server/ArgoCD/Notifications
        run: go build -v ./...     
      
      - name: Build Docker Image
        working-directory: ./app/server/ArgoCD/Notifications
        run: docker build . --file Dockerfile --tag notifications 
